name: Deploy Dev Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - development
      
      deploy-base-infra:
        description: "Deploy Base Infrastructure"
        required: true
        type: boolean
        default: true

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment : ${{ inputs.environment }}"
          echo "Deploy Base Infra : ${{ inputs.deploy-base-infra }}"
      
      - name: Provision Development Resources
        run: |
          echo "Checking AZ"
          if command -v az >/dev/null 2>&1; then
              echo "Azure CLI is installed."
              az version
          else
              echo "Azure CLI is not installed."
              exit 1
          fi
