name: Deploy Dev Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - development
      
      deploy-base-infra:
        description: "Deploy Base Infrastructure"
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Show inputs
        run: |
          echo "Environment : ${{ inputs.environment }}"
          echo "Deploy Base Infra : ${{ inputs.deploy-base-infra }}"
      
      - name: Check AZ Command
        run: |
          echo "Checking AZ"
          if command -v az >/dev/null 2>&1; then
              echo "Azure CLI is installed."
              az version
          else
              echo "Azure CLI is not installed."
              exit 1
          fi
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
      
      - name: Verify Azure Login
        shell: bash
        run: |
          set -euo pipefail

          echo "Current account:"
          az account show --output table

          echo
          echo "Current subscription:"
          az account show --query "{Name:name, Subscription:id, Tenant:tenantId}" --output table
