name: Deploy Infrastructure Template

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - development
          - production
      
      deploy-base-infra:
        description: "Deploy Base Infrastructure"
        required: true
        type: boolean
        default: true
      
      deploy-security:
        description: "Deploy Module Security"
        required: true
        type: boolean
        default: false
      
      deploy-cluster:
        description: "Deploy Module Cluster"
        required: true
        type: boolean
        default: false

jobs:
  echo-parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment : ${{ inputs.environment }}"
          echo "Deploy Base Infra : ${{ inputs.deploy-base-infra }}"
          echo "Deploy Security Module : ${{ inputs.deploy-security }}"
          echo "Deploy Cluster Module : ${{ inputs.deploy-cluster }}"
